name: geog0111
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.4
  - pip
  - git
  - jupyter
  - mkdocs
  - sphinx
  - pip:
    - cylog
    - nbsphinx
    - mkdocs-jupyter
    - urlpath
    - mknotebooks
    - mkdocs-material
    - mkdocs-exclude
    - mkdocs-git-revision-date-localized-plugin
# conda env update -n base -f environment.yml
# python -m ipykernel install --name=conda-env-geog0111-geog0111-py --display-name 'conda env:geog0111-geog0111'
